development:
  adapter: postgresql
  database: qbrick_development
  username: screenconcept
  password:
  host: localhost
  encoding: unicode
  pool: 5
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>

test:
  adapter: postgresql
  database: qbrick_test
  username: screenconcept
  password:
  host: localhost
  encoding: unicode
  pool: 5
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>
